#!/bin/bash

BOLD="\e[1m"
DIM="\e[2m"
RESET="\e[0m"
RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
CYAN="\e[36m"

DEFAULT_CERTS_DIR="$HOME/.android-certs"
SAMPLE_SUBJECT="/C=US/ST=California/L=Mountain View/O=Android/OU=Android/CN=Android/emailAddress=android@android.com"
KEYS=(bluetooth certs cyngn-app media networkstack otakey nfc platform releasekey sdk_sandbox shared testcert testkey verity)

die() { echo -e "${RED}error: $*${RESET}" >&2; exit 1; }

ask() {
    # ask <prompt> <default: y|n> → returns 0 for yes, 1 for no
    local prompt="$1" default="${2:-n}" choice
    echo -en "$prompt"
    read -r choice </dev/tty
    [[ -z "$choice" ]] && choice="$default"
    [[ "$choice" =~ ^[Yy] ]]
}

read_field() {
    echo -en "${DIM}$1:${RESET} "
    read -r val </dev/tty
    echo "$val"
}

# ── Header ────────────────────────────────────────────────────────────────────
clear
echo -e "${BOLD}AOSP Signing Key Generator${RESET}"
echo -e "${DIM}Signs system components: platform, media, OTA, etc.${RESET}"
echo -e "${RED}Keep keys private — loss means inability to ship updates.${RESET}"
echo

# ── Output directory ──────────────────────────────────────────────────────────
echo -en "${BOLD}Output dir${RESET} [${CYAN}${DEFAULT_CERTS_DIR}${RESET}]: "
read -r certs_dir </dev/tty
[[ -z "$certs_dir" ]] && certs_dir="$DEFAULT_CERTS_DIR"

if [[ -d "$certs_dir" ]]; then
    existing_keys=()
    for k in "${KEYS[@]}"; do
        [[ -f "$certs_dir/$k.pk8" || -f "$certs_dir/$k.x509.pem" ]] && existing_keys+=("$k")
    done

    if [[ ${#existing_keys[@]} -gt 0 ]]; then
        echo -e "${YELLOW}Existing keys:${RESET} ${existing_keys[*]}"
        echo "  [a] remove all and regenerate"
        echo "  [s] select keys to remove"
        echo "  [q] quit"
        echo -en "${BOLD}Choice:${RESET} "
        read -r dir_choice </dev/tty

        case "$dir_choice" in
            a)
                rm -rf "$certs_dir" || die "failed to remove $certs_dir"
                echo -e "${GREEN}removed.${RESET}"
                ;;
            s)
                echo -e "${DIM}Enter key names to remove (space-separated):${RESET}"
                echo -e "${DIM}Available: ${existing_keys[*]}${RESET}"
                echo -en "> "
                read -r -a keys_to_remove </dev/tty
                for k in "${keys_to_remove[@]}"; do
                    rm -f "$certs_dir/$k.pk8" "$certs_dir/$k.x509.pem"
                    echo -e "  removed $k"
                done
                ;;
            q|*)
                echo "exiting."
                exit 0
                ;;
        esac
    fi
fi

mkdir -p "$certs_dir" || die "failed to create $certs_dir"

# ── Subject ───────────────────────────────────────────────────────────────────
echo
echo -e "${DIM}Sample subject: $SAMPLE_SUBJECT${RESET}"
if ask "${BOLD}Use sample subject?${RESET} [Y/n]: " y; then
    subject="$SAMPLE_SUBJECT"
else
    subject=""
    for field in C ST L O OU CN emailAddress; do
        val=$(read_field "$field")
        subject+="/$field=$val"
    done
fi
[[ -z "$subject" ]] && die "subject cannot be empty."

[[ ! -x "./development/tools/make_key" ]] && die "make_key not found — run from AOSP root."

# ── Generate ──────────────────────────────────────────────────────────────────
echo
echo -e "${BOLD}Generating ${#KEYS[@]} keys${RESET} → ${CYAN}$certs_dir${RESET}"
echo -e "${DIM}────────────────────────────────────────${RESET}"

failed=()
for key in "${KEYS[@]}"; do
    # skip if both files already exist (were not removed)
    if [[ -f "$certs_dir/$key.pk8" && -f "$certs_dir/$key.x509.pem" ]]; then
        printf "  %-14s ${DIM}skipped (exists)${RESET}\n" "$key"
        continue
    fi
    echo -e "  ${DIM}[ $key ]${RESET}"
    ./development/tools/make_key "$certs_dir/$key" "$subject"
    if [[ -f "$certs_dir/$key.pk8" && -f "$certs_dir/$key.x509.pem" ]]; then
        printf "  %-14s ${GREEN}ok${RESET}\n" "$key"
    else
        printf "  %-14s ${RED}failed${RESET}\n" "$key"
        failed+=("$key")
    fi
done

echo -e "${DIM}────────────────────────────────────────${RESET}"
[[ ${#failed[@]} -gt 0 ]] && die "failed keys: ${failed[*]}"
echo -e "${GREEN}all keys generated.${RESET}"

# ── Makefile ──────────────────────────────────────────────────────────────────
MAKEFILE_PATH="$certs_dir/keys.mk"
cat > "$MAKEFILE_PATH" <<EOF
# Generated by aosp-keygen
SIGNING_KEY_PATH ?= $certs_dir
RELEASE_KEY      := \$(SIGNING_KEY_PATH)/releasekey

PRODUCT_DEFAULT_DEV_CERTIFICATE := \$(RELEASE_KEY)
PRODUCT_OTA_PUBLIC_KEYS          := \$(RELEASE_KEY)
EOF

echo
echo -e "${BOLD}keys.mk${RESET} → ${CYAN}$MAKEFILE_PATH${RESET}"
echo -e "${DIM}Include via: include \$(SIGNING_KEY_PATH)/keys.mk${RESET}"
echo -e "${GREEN}done.${RESET}"
